package com.amazonaws.mobilehelper.auth.signin.buttons;
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.16
//

import android.content.Context;
import android.graphics.Color;
import android.support.annotation.Nullable;
import android.util.AttributeSet;
import com.amazonaws.mobilehelper.R;


public class GoogleButton extends SignInButton {

    /** Button corner radius. */
    private static final int CORNER_RADIUS = 4;

    /** Button background color. */
    private static final int GOOGLE_BACKGROUND_COLOR = Color.WHITE;

    /** Button background color when pressed. */
    private static final int GOOGLE_BACKGROUND_COLOR_PRESSED = Color.LTGRAY;

    /** Button top shadow color. */
    private static final int TOP_BUTTON_SHADOW_COLOR = 0xFFCCCCCC;

    /** Button top shadow thickness in pixels. */
    private static final int BUTTON_TOP_SHADOW_THICKNESS = (int) dp(1);

    /** Button bottom shadow thickness in pixels. */
    private static final int BUTTON_BOTTOM_SHADOW_THICKNESS = (int) dp(2);

    /** Text Color. */
    private static final int TEXT_COLOR = Color.DKGRAY;


    public GoogleButton(Context context) {
        this(context, null);
    }

    public GoogleButton(Context context, @Nullable AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public GoogleButton(Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr,
            new SignInButtonAttributes()
                .withCornerRadius(CORNER_RADIUS)
                .withBackgroundColor(GOOGLE_BACKGROUND_COLOR)
                .withBackgroundColorPressed(GOOGLE_BACKGROUND_COLOR_PRESSED)
                .withTopShadowColor(TOP_BUTTON_SHADOW_COLOR)
                .withBottomShadowColor(Color.DKGRAY)
                .withTopShadowThickness(BUTTON_TOP_SHADOW_THICKNESS)
                .withBottomShadowThickness(BUTTON_BOTTOM_SHADOW_THICKNESS)
                .withTextColor(TEXT_COLOR)
                .withDefaultTextResourceId(R.string.default_google_button_text)
                .withImageIconResourceId(R.mipmap.google_icon)
        );
    }

}
