package com.amazonaws.mobile.user.signin;
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.16
//

import android.net.Uri;
import android.util.Log;

import com.amazonaws.mobilehelper.auth.IdentityProvider;
import com.amazonaws.mobilehelper.auth.user.AbstractIdentityProfile;
import com.amazonaws.mobilehelper.auth.user.IdentityProfile;
import com.amazonaws.mobilehelper.auth.user.ProfileRetrievalException;
import com.google.android.gms.auth.api.signin.GoogleSignInAccount;

/**
 * Identity Profile for Google Provider.
 */
public class GoogleIdentityProfile extends AbstractIdentityProfile {
    /** Log tag. */
    private static final String LOG_TAG = GoogleIdentityProfile.class.getSimpleName();

    /**
     *
     * @param provider the identity provider for which this is loading the profile.
     */
    public IdentityProfile loadProfileInfo(final IdentityProvider provider) throws ProfileRetrievalException {
        if (!provider.refreshUserSignInState()) {
            throw new ProfileRetrievalException(
                "Can't load user info, due to no longer signed in with " + provider.getDisplayName());
        }

        final GoogleSignInProvider googleSignInProvider = (GoogleSignInProvider) provider;
        final GoogleSignInAccount signedInAccount = googleSignInProvider.getSignedInAccount();

        userName = signedInAccount.getDisplayName();
        final Uri photoUrl = signedInAccount.getPhotoUrl();
        if (photoUrl != null) {
            Log.d(LOG_TAG, "Successfully Loaded image url.");
            userImageUrl = photoUrl.toString();
        } else {
            Log.w(LOG_TAG, "Failed to load image url.");
            userImageUrl = null;
        }
        return this;
    }
}
